const base = require("../base");
function execute() {
    base.db[user].modulo = 14;
    return [

        "COSTO DE VALORES UNIVERSITARIOS",
        "PRORROGA TITULO DE BACHILLER Bs. 5",
        "PRORROGA CERTIFICADO DE NACIMIENTO Bs. 3",
        "CERTIFICADO DE HABILITACION Bs. 4",
        "FORMULARIO CAMBIO DCARRERA Bs. 25",
        "FORMULARIO DIPLOMA DBACHILLER Bs. 20",
        "DIPLOMA DE BACHILLEHUMANIDADES Bs. 175",
        "DIPLOMA DE BACHILLECEMA Bs. 175",
        "DIPLOMA DE BACHILLER INDUSTRIAL Bs. 175",
        "DIPLOMA DE BACHILLER COMERCIAL Bs. 175",
        "TITULO PROFESIONAL Bs. 315",
        "TITULO PROFESIONAL EXTRANJERO Bs. 1685",
        "DIPLOMA POSGRADO Bs. 1000",
        "DIPLOMA ACADEMICO Bs. 215",
        "DIPLOMA ACADEMICO EXTRANJERO Bs. 1215",
        "TIMBRES Bs. 1",
        "TIMBRES Bs. 5",
        "TIMBRES Bs. 10",
        "TIMBRES Bs. 25",
        "FOLDER TRAMITE DE TITULO BACH., LEGALIZADO Bs. 5",
        "FORM. SOLICITUD DIPLOMA ACADEMICO Bs.10",
        "LEGALIZACION TITULOS Bs. 70",
        "CHEQUE REVERTIDO Bs. 50",
        "FORMULARIO DE REINSCRIPCION Bs. 10",
        "CERTIFICADO DE CALIFICACIONES Bs. 3",
        "CERTIFICADO CONCLUSION DE ESTUDIOS Bs. 10",
        "FORM. CERTIFICACION BIBLIOTECA Bs. 5",
        "FORM. CARRERAS PARALELAS",
        "CERT. CONCLUSION DE EST. TEC. MEDIO",
        "CERT. CONCLUSION DE EST. TEC. SUPERIOR Bs. 10",
        "CERTIFICADO SUPLETORIO NACIONAL Bs. 260",
        "CERTIFICADO SUPLETORIO EXTRANJERO Bs. 580",

        "GRACIAS POR SU ATENCION DIGITE OK ",
    ];
}

exports.execute = execute;